In [2]:
# 读取 CSV 文件
data <- read.csv('/home/houerjia/program/experments/PBMC_handoff/PBMC_sqlou/fig2/fig2c_translation_efficiency_changes_with_gene_info_byH.csv')

# 定义要筛选的基因列表
genes_to_select <- c('TNFSF13', 'CCL25', 'CD93', 'CD82', 'CD24', 'RELT')

# 筛选出指定基因的数据
selected_data <- data[data$external_gene_name %in% genes_to_select, ]

# 查看筛选后的数据
selected_data

     Transcript         TE_H      TE_W      log2_fold_change regulation
473  ENSSSCT00000007788 0.5406641 10.461856 4.274262         up
2447 ENSSSCT00000047746 0.5096332 22.289983 5.450792         up
2483 ENSSSCT00000048271 0.3951298 31.332529 6.309191         up
3261 ENSSSCT00000061883 0.3036328  3.347278 3.462589         up
4294 ENSSSCT00000102451 1.3608582 21.594008 3.988042         up
4330 ENSSSCT00000104492 0.2678296  3.879765 3.856582         up
     ensembl_gene_id    external_gene_name gene_biotype
473  ENSSSCG00000007116 CD93               protein_coding
2447 ENSSSCG00000013593 CCL25              protein_coding
2483 ENSSSCG00000036521 TNFSF13            protein_coding
3261 ENSSSCG00000014825 RELT               protein_coding
4294 ENSSSCG00000029521 CD82               protein_coding
4330 ENSSSCG00000056379 CD24               protein_coding
     description
473  CD93 molecule [Source:VGNC Symbol;Acc:VGNC:108710]
2447 C-C motif chemokine ligand 25 [Source:NCBI gene (formerly Entrezgene);Acc:448799]
2483 TNF superfamily member 13 [Source:VGNC Symbol;Acc:VGNC:98380]
3261 RELT TNF receptor [Source:VGNC Symbol;Acc:VGNC:92209]
4294 CD82 molecule [Source:VGNC Symbol;Acc:VGNC:86432]
4330 CD24 molecule [Source:UniProtKB Gene Name;Acc:K7GMK8]

In [6]:
# 选择指定列组成新表
new_data <- selected_data[, c("external_gene_name","ensembl_gene_id","TE_H", "TE_W")]

# 输出新表
new_data

     external_gene_name ensembl_gene_id    TE_H      TE_W
473  CD93               ENSSSCG00000007116 0.5406641 10.461856
2447 CCL25              ENSSSCG00000013593 0.5096332 22.289983
2483 TNFSF13            ENSSSCG00000036521 0.3951298 31.332529
3261 RELT               ENSSSCG00000014825 0.3036328  3.347278
4294 CD82               ENSSSCG00000029521 1.3608582 21.594008
4330 CD24               ENSSSCG00000056379 0.2678296  3.879765

In [9]:
# 使用 colnames() 修改列名
colnames(new_data)[colnames(new_data) == 'TE_H'] <-'H'
colnames(new_data)[colnames(new_data) == 'TE_W'] <-'W'
colnames(new_data)[colnames(new_data) == 'external_gene_name'] <- ''
colnames(new_data)[colnames(new_data) == 'ensembl_gene_id'] <- ''

colnames(new_data)

[1] ""  ""  "H" "W"

In [10]:
write.csv(new_data, "/home/houerjia/program/experments/PBMC_handoff/PBMC_sqlou/fig2/fig2f_selected_genes_data_byH.csv", row.names = FALSE)